language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install nose coverage
  - pip install coveralls
  # command to run tests
script:
  - nosetests --with-coverage --cover-package skytap
after_success:
  - coveralls
