# this is a configuration template for skynet.  Copy this file to ./config.yml and populate with variables for your environment
#

base_url:       https://cloud.skytap.com                                # base url for rest queries
user:           <skytap_user_name>                                      # username
token:          <api_token>                                             # API Token

working_dir:    <path to skynet.py>                                     # this is the path to the skynet.py file
control_dir:    <path to skytap-control repository>                     # this is the path to the skytap-control directory
temp_dir:       <path to temp directory>                                # path to a temporary directory

